---
- hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

  tasks:
    - name: Enable apache
      apache2_module:
        name: rewrite
        state: present
        notify: restart apache
